modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License 3"
issueTrackerURL="https://github.com/MrCrayfish/Backpacked/issues"

[[mods]]
modId="backpacked"
version="1.10.2"
displayName="Backpacked"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=backpacked"
displayURL="https://mrcrayfish.com/mods?id=backpacked"
logoFile="backpacked.png"
authors="MrCrayfish"
credits="JamesTheMaker, "
description="Adds a simple backpack to store more items"

[[dependencies.backpacked]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="curios"
    mandatory=false
    versionRange="[1.16.3-4.0.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.backpacked]]
    modId="controllable"
    mandatory=false
    versionRange="[0.11.0,)"
    ordering="AFTER"
    side="CLIENT"

[modproperties.backpacked]
    catalogueItemIcon="backpacked:backpack" #Support for Catalogue mod
    configuredBackground="minecraft:textures/block/terracotta.png" #Support for Configured mod