modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="backpacked"
version="1.8.1"
displayName="Backpacked"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/backpacked/update.json"
displayURL="https://mrcrayfish.com/mods?id=backpacked"
logoFile="backpacked.png"
credits=""
authors="MrCrayfish"
description="Adds a simple backpack to store more items"

[[dependencies.backpacked]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="curios"
    mandatory=false
    versionRange="[2.0,)"
    ordering="AFTER"
    side="BOTH"